#!/bin/bash

revert() {
    xset dpms 0 0 0
}

image=$(mktemp --suffix=.png)
shot=(scrot)
lockcmd=(i3lock -i "$image")
pixelate=(-scale 10% -scale 1000%)
hue=(-level 0%,100%,1)

trap 'rm -f "$image"' EXIT
trap revert SIGHUP SIGINT SIGTERM

"${shot[@]}" "$image"

color=$(convert "$image" -gravity center -crop 100x100+0+0 +repage -colorspace hsb \
                -resize 1x1 txt:- | awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}');
value="60"

if [[ $color -gt $value ]]; then #white background image and black text
    bw="black"
    txtcolor=333333ff
    ringcolor=333333ff
    insidecolor=abababff
    icon="$HOME/script/awlock/icon/LOCK_DARK.png"
else
    bw="white"
    txtcolor=ffffffff
    ringcolor=ffffffff
    insidecolor=373445ff
    icon="$HOME/script/awlock/icon/LOCK.png"
fi

pretty=(--insidecolor="$insidecolor" --ringcolor="$ringcolor" --line-uses-inside
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:h-80"
    --radius=20 --ring-width=4 --veriftext="" --wrongtext="" --noinputtext=""
    --clock --timepos='x+200:h-80' --timecolor="$txtcolor"
    --datecolor="$txtcolor" --force-clock)

addimg=(-font FreeMono-Gras -pointsize 26 -fill "$bw" -gravity center -annotate +0+100 "Password please" "$icon" -gravity center -composite)

transform () {
    screens=$1
    for scr in $screens
    do
        croped=$(mktemp --suffix=.png)
        decl=$(echo "$scr" | sed 's/[0-9]*x[0-9]*//')
        convert "$image" -crop "$scr" -scale 10% -scale 1000% "$croped"
        composite -compose Over -gravity Center "$icon" "$croped" "$croped"
        composite -compose Over -geometry "$decl" -gravity NorthWest "$croped" \
                  "$image" "$image"
        rm -f "$croped"
    done
}

screens=$(xrandr -q | awk '/[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/ && /primary/ {print $4} /[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/ && !/primary/ {print $3}')

if [[ $(echo "$screens" | wc -l) == 1 ]]
then
    convert "$image" "${hue[@]}" "${pixelate[@]}" "${addimg[@]}" "$image"
else
    transform "$screens"
fi

# feh "$image"
[[ "$#" -ge 1 && "$1" == '-s' ]] || xset +dpms dpms 5 5 5
[[ "$#" -ge 1 && "$1" == '-s' ]] && (sleep 2; systemctl suspend) &
i3lock -nei "$image" "${pretty[@]}" 2> /dev/null || i3lock -neui "$image"
revert
rm -f "$image"
