#!/bin/bash

figs=$(figlist | awk '
BEGIN { i=0; }
/Figlet control files in this directory/ { i=0; }
/Figlet fonts in this directory/ { i=1; next; }
/.*/ { if (i == 1) print $0; }')

fig=$(echo "$figs" | sort -R | head -1)

echo "$1" | figlet -w 100 -f "$fig"
