#!/usr/bin/lua

local pretty = require "pl.pretty"

local pfile = io.popen ("figlist")
local lines = pfile:read "*a"
pfile:close ()

local fonts = {}
from = false
for line in lines:gmatch ("[^\n]*") do
  if line == "Figlet control files in this directory:" then break end
  if from then
    fonts[#fonts+1] = line
  end
  if line == "Figlet fonts in this directory:" then from = true end
end

local ipt = io.read "*l"
math.randomseed(os.time ())
local selected_font = fonts[math.random(1, #fonts)]

os.execute (string.format ("echo %s | figlet -w 100 -f %s", ipt, selected_font))
