#!/bin/bash

BG=0
if [[ "$1" == "--background" ]]
then
    BG=1
    shift
fi

TMUX_S=$(tmux display-message -p "#S")
if test "$TMUX_S" != "0"
then
    DAEMONIZE="--daemon=$TMUX_S"
    SOCKET="--socket=$TMUX_S"
else
    DEAMONIZE="--daemon"
fi
if [[ $(ps aux | grep "emacs $DAEMONIZE" | wc -l) == 1 ]]
then
    emacs "$DAEMONIZE"
fi
# if jobs | grep "emacsclient" >/dev/null 2>&1
# then
#     emacsclient "$SOCKET" -n $*
#     fg '%emacsclient'
# else

# fi

if [[ "$BG" -eq 1 ]]
then
    emacsclient "$SOCKET" -c $* &
else
    emacsclient "$SOCKET" -c $*
fi
